#!/usr/bin/env python3
"""
CogRepo Setup Wizard

Interactive setup for configuring CogRepo with secure API key storage.
Creates ~/.cogrepo/config.yaml with proper permissions.

Usage:
    python cogrepo_setup.py
"""

import os
import sys
import stat
from pathlib import Path

def get_input(prompt: str, default: str = None, secret: bool = False) -> str:
    """Get user input with optional default."""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "

    if secret:
        try:
            import getpass
            value = getpass.getpass(prompt)
        except Exception:
            value = input(prompt)
    else:
        value = input(prompt)

    return value.strip() or default or ""


def setup():
    """Run the setup wizard."""
    print()
    print("=" * 60)
    print("  CogRepo Setup Wizard")
    print("=" * 60)
    print()
    print("This wizard will configure CogRepo with secure settings.")
    print()

    # Determine config location
    config_dir = Path.home() / '.cogrepo'
    config_file = config_dir / 'config.yaml'

    # Check for existing config
    if config_file.exists():
        print(f"Existing config found: {config_file}")
        response = get_input("Overwrite existing config?", "n")
        if response.lower() not in ('y', 'yes'):
            print("\nSetup cancelled. Existing config preserved.")
            return False
        print()

    # Get API key
    print("Step 1: Anthropic API Key")
    print("-" * 40)
    print("Get your key from: https://console.anthropic.com/settings/keys")
    print()

    # Check for existing env var
    existing_key = os.getenv('ANTHROPIC_API_KEY')
    if existing_key:
        masked = f"{existing_key[:12]}...{existing_key[-4:]}" if len(existing_key) > 16 else "***"
        print(f"Found ANTHROPIC_API_KEY in environment: {masked}")
        use_existing = get_input("Use this key?", "y")
        if use_existing.lower() in ('y', 'yes', ''):
            api_key = existing_key
        else:
            api_key = get_input("Enter your Anthropic API key", secret=True)
    else:
        api_key = get_input("Enter your Anthropic API key", secret=True)

    if not api_key:
        print("\nNo API key provided. You can add it later to ~/.cogrepo/config.yaml")
        print("Or set the ANTHROPIC_API_KEY environment variable.")
        api_key = None
    elif not api_key.startswith('sk-ant-'):
        print("\nWarning: Key doesn't look like an Anthropic key (should start with 'sk-ant-')")
        proceed = get_input("Continue anyway?", "n")
        if proceed.lower() not in ('y', 'yes'):
            print("\nSetup cancelled.")
            return False

    print()
    print("Step 2: Model Selection")
    print("-" * 40)
    print("Available models:")
    print("  1. claude-3-5-haiku (fast, cheap - recommended for enrichment)")
    print("  2. claude-sonnet-4 (balanced)")
    print("  3. claude-opus-4 (most capable, expensive)")
    print()

    model_choice = get_input("Select enrichment model", "1")
    models = {
        "1": "claude-3-5-haiku-20241022",
        "2": "claude-sonnet-4-20250514",
        "3": "claude-opus-4-20250514"
    }
    enrichment_model = models.get(model_choice, models["1"])

    print()
    print("Step 3: Confirm Settings")
    print("-" * 40)
    print(f"  Config location: {config_file}")
    print(f"  API key: {'Configured' if api_key else 'Not set'}")
    print(f"  Enrichment model: {enrichment_model}")
    print()

    confirm = get_input("Save these settings?", "y")
    if confirm.lower() not in ('y', 'yes', ''):
        print("\nSetup cancelled.")
        return False

    # Create config directory with secure permissions
    try:
        config_dir.mkdir(mode=0o700, exist_ok=True)
    except Exception as e:
        print(f"\nError creating config directory: {e}")
        return False

    # Build config content
    config_content = f"""# CogRepo Configuration
# Generated by cogrepo_setup.py
# Location: {config_file}

anthropic:
  api_key: {api_key if api_key else '# Add your API key here'}
  model: {enrichment_model}
  haiku_model: claude-3-5-haiku-20241022
  temperature: 0.3
  max_retries: 3

enrichment:
  batch_size: 10
  use_haiku_for_extraction: true
  skip_if_enriched: true

search:
  use_semantic: true
  use_fts5: true
  default_limit: 50

embeddings:
  model: all-MiniLM-L6-v2
  batch_size: 64
"""

    # Write config file
    try:
        with open(config_file, 'w') as f:
            f.write(config_content)

        # Set secure permissions (owner read/write only)
        os.chmod(config_file, stat.S_IRUSR | stat.S_IWUSR)

    except Exception as e:
        print(f"\nError writing config file: {e}")
        return False

    print()
    print("=" * 60)
    print("  Setup Complete!")
    print("=" * 60)
    print()
    print(f"Config saved to: {config_file}")
    print(f"Permissions: 600 (owner read/write only)")
    print()
    print("Next steps:")
    print("  1. Start the web UI:  cd cogrepo-ui && python app.py")
    print("  2. Import data:       python cogrepo_import.py --help")
    print("  3. Run tests:         pytest tests/ -v")
    print()

    return True


def verify():
    """Verify the current configuration."""
    print()
    print("CogRepo Configuration Status")
    print("=" * 60)

    # Check config file
    config_file = Path.home() / '.cogrepo' / 'config.yaml'
    print(f"\nConfig file: {config_file}")
    print(f"  Exists: {config_file.exists()}")

    if config_file.exists():
        # Check permissions
        mode = os.stat(config_file).st_mode
        is_secure = (mode & 0o777) == 0o600
        print(f"  Permissions: {oct(mode & 0o777)} {'(secure)' if is_secure else '(WARNING: not secure)'}")

        # Check content
        try:
            import yaml
            with open(config_file) as f:
                config = yaml.safe_load(f)

            if config and 'anthropic' in config:
                key = config['anthropic'].get('api_key', '')
                if key and not key.startswith('#'):
                    masked = f"{key[:12]}...{key[-4:]}" if len(key) > 16 else "***"
                    print(f"  API key: {masked}")
                else:
                    print("  API key: Not configured")
                print(f"  Model: {config['anthropic'].get('model', 'default')}")
        except Exception as e:
            print(f"  Error reading config: {e}")

    # Check environment variable
    env_key = os.getenv('ANTHROPIC_API_KEY')
    print(f"\nEnvironment variable ANTHROPIC_API_KEY:")
    if env_key:
        masked = f"{env_key[:12]}...{env_key[-4:]}" if len(env_key) > 16 else "***"
        print(f"  Set: {masked}")
    else:
        print("  Not set")

    # Try loading config through the system
    print("\nConfiguration resolution:")
    try:
        sys.path.insert(0, str(Path(__file__).parent))
        from core.config import get_config, reset_config
        reset_config()
        config = get_config()
        print(f"  API key configured: {config.anthropic.is_configured}")
        print(f"  Model: {config.anthropic.model}")
        print(f"  Haiku model: {config.anthropic.haiku_model}")
    except Exception as e:
        print(f"  Error loading config: {e}")

    print()


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description="CogRepo Setup Wizard")
    parser.add_argument('--verify', action='store_true', help="Verify current configuration")

    args = parser.parse_args()

    if args.verify:
        verify()
    else:
        success = setup()
        sys.exit(0 if success else 1)
